# docker-compose.dev.yml

services:
  # Serviço da API em modo desenvolvimento
  api:
    container_name: levantamento-api-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npx nodemon --legacy-watch server.js
    depends_on:
      - minio

  # Serviço do MinIO para armazenamento das fotos
  minio:
    image: minio/minio:latest
    container_name: levantamento-minio-dev
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    volumes:
      - ./minio-data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      - MINIO_SERVER_URL=${MINIO_PUBLIC_URL} 
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:${MINIO_CONSOLE_PORT} 
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"

volumes:
  mongodb-data: