# docker-compose.yml

services:
  # Serviço da API
  api:
    container_name: levantamento-api
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ./.env
    depends_on:
      - minio
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Serviço do MinIO para armazenamento das fotos
  minio:
    image: minio/minio:latest
    container_name: levantamento-minio
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    volumes:
      - ./minio-data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"