# docker-compose.yml

services:
  # Serviço da API
  api:
    container_name: levantamento-api
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - minio

  mongo:
    image: mongo:8
    container_name: levantamento-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet --logpath /dev/null
    restart: always

  # Serviço do MinIO para armazenamento das fotos
  minio:
    image: minio/minio:latest
    container_name: levantamento-minio
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    volumes:
      - ./minio-data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      - MINIO_SERVER_URL=${MINIO_PUBLIC_URL} 
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:${MINIO_CONSOLE_PORT} 
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"

volumes:
  mongo-data: