# docker-compose.dev.yml

services:
  # Serviço da API em modo desenvolvimento
  api:
    container_name: levantamento-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npx nodemon --legacy-watch server.js
    depends_on:
      - mongo
      - minio

  mongo:
    image: mongo:8
    container_name: levantamento-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-dev:/data/db
    command: mongod --quiet --logpath /dev/null
    restart: always

  # Serviço do MinIO para armazenamento das fotos
  minio:
    image: minio/minio:latest
    container_name: levantamento-minio
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    volumes:
      - ./minio-data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      - MINIO_BROWSER_REDIRECT_URL=http://localhost:${MINIO_CONSOLE_PORT} 
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"

volumes:
  mongo-data-dev:
